theme: osuny
enableRobotsTXT: true
removePathAccents: true
params:
  plausible: iut.u-bordeaux-montaigne.fr
  pages:
    index:
      truncate_description: 0
  summary:
    position: hero
  search:
    active: truep
  logo:
    header: "/assets/images/logo.svg"
    footer: "/assets/images/logo.svg"
