title: "IUT Bordeaux Montaigne"
languageCode: "fr-FR"
theme: "osuny-school"
paginate: 18
permalinks:
  posts: /actualites/:year/:month/:day/:slug/
  authors: /auteurs/:slug/
  categories: /actualites/categories/:slug/
taxonomies:
  author: "authors"
