title: "IUT Bordeaux Montaigne"
languageCode: "fr-FR"
theme: "osuny-school"
paginate: 18
permalinks:
  posts: /actualites/:year/:month/:day/:slug/
  persons: /equipe/:slug/
  categories: /actualites/categories/:slug/
