categories: /actualites/:slug/
posts: /actualites/:year/:month/:day/:slug/
diplomas: /formation/offre-de-formation/diplomes/:slug/
persons: /notre-institut/ressources/equipe/:slug/
administrators: /notre-institut/ressources/equipe/:slug/roles/
authors: /notre-institut/ressources/equipe/:slug/actualites/
researchers: /notre-institut/ressources/equipe/:slug/papers/
teachers: /notre-institut/ressources/equipe/:slug/programs/
