name = "Osuny School"
license = "MIT"
licenselink = "https://github.com/noesya/osuny-hugo-school/blob/master/LICENSE"
description = ""
homepage = "https://www.osuny.org/"
tags = []
features = []
min_version = "0.41.0"

[author]
  name = "noesya"
  homepage = "https://www.noesya.coop"
