# Setup for percy snapshots : by default only root pages are snapshot

version: 2
static:
  base-url: /
  clean-urls: false
  include: 
    - 'index.html'
    - 'offre-de-formation/bachelor-universitaire-de-technologie/metiers-du-multimedia-et-de-l-internet/index.html'
    - 'equipe/arnaud-levy/index.html'
    - 'vie-etudiante/scolarite/etre-candidat/index.html'