title: IUT Bordeaux Montaigne
languageCode: fr-FR
theme: osuny-school
paginate: 18
permalinks:
  posts:          /actualites/:year/:month/:day/:slug/
  categories:     /actualites/:sections/:slug/
  persons:        /equipe/:slug/
  authors:        /equipe/:slug/actualites/
  administrators: /equipe/:slug/administration/
  researchers:    /equipe/:slug/publications/
  teachers:       /equipe/:slug/formations/
taxonomies:
  administrator:  administrators
  author:         authors
  category:       categories
  researcher:     researchers
  teacher:        teachers
