title: IUT Bordeaux Montaigne
languageCode: fr-FR
theme: osuny-school
paginate: 18
permalinks:
  authors: /auteurs/:slug/
  categories: /actualites/categories/:slug/
  posts: /actualites/:year/:month/:day/:slug/
taxonomies:
  category: categories
  author: authors
