title: IUT Bordeaux Montaigne
languageCode: fr-FR
theme: osuny-school
paginate: 18
permalinks:
  administrators: /administration/:slug/
  authors: /auteures/:slug/
  categories: /actualites/:sections/:slug/
  posts: /actualites/:year/:month/:day/:slug/
  researchers: /chercheuses/:slug/
  teachers: /enseignantes/:slug/
taxonomies:
  administrator: administrators
  author: authors
  category: categories
  researcher: researchers
  teacher: teachers
