name: Percy

on:
  push:
    branches:
      - main
      - v2

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
          fetch-depth: 1
      - name: Percy Test
        run: npx @percy/cli snapshot public/ 
