name: Percy

on:
  push:
    branches:
      - v2

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Percy Test
        run: npx @percy/cli snapshot public/ 

# You need to add PERCY_TOKEN in your repository's secrets to run tests
